name: Update MyREADME

on:
  schedule:
    - cron: "5 2/23 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:

      - uses: actions/checkout@v4.2.2
      - uses: readme-workflows/recent-activity@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
